ollama rm gemma2:2b
ollama rm codegemma:latest
ollama rm mistral:latest
ollama rm phi3:14b
ollama rm phi3:latest
ollama rm mistral-nemo:latest
ollama rm gemma2:latest
ollama rm llama3.1:latest
ollama rm gemma:latest
ollama rm llama3:latest
ollama rm qwen2:latest
ollama rm qwen2:7b
ollama rm aya:latest
ollama rm gemma:7b
ollama rm gemma:2b
ollama rm openchat:latest
ollama rm neural-chat:latest
ollama rm mistral-openorca:latest