-- Sample data for H7_NOTE table
INSERT INTO habits7_note (note_name, url, note_type, note, tags, created_by, created_at, updated_by, updated_at) 
VALUES 
    ('Python Best Practices', 
     'https://docs.python.org/3/tutorial/index.html',
     'learning',
     'Key points from Python documentation: 1) Use virtual environments 2) Follow PEP 8 3) Write docstrings',
     'python,programming,best-practices',
     'USERNAME',
     'DATA_DATE',
     'USERNAME',
     'DATA_DATE'),

    ('ML Project Ideas',
     'https://paperswithcode.com',
     'research',
     'Potential project ideas: 1) Time series forecasting 2) Image classification 3) Natural language processing',
     'machine-learning,AI,projects',
     'USERNAME',
     'DATA_DATE',
     'USERNAME',
     'DATA_DATE'),

    ('Daily Journal Entry',
     '',
     'journal',
     'Today I learned about database design and SQL optimization. Need to practice more complex queries.',
     'journal,reflection,learning',
     'USERNAME',
     'DATA_DATE',
     'USERNAME',
     'DATA_DATE'),

    ('Task Manager Project Plan',
     'https://github.com/myrepo/task-manager',
     'project',
     'Project milestones: 1) Database setup 2) User authentication 3) Task CRUD operations 4) UI development',
     'project-management,planning,development',
     'USERNAME',
     'DATA_DATE',
     'USERNAME',
     'DATA_DATE'),

    ('SQL Learning Resources',
     'https://mode.com/sql-tutorial',
     'learning',
     'Important SQL concepts: JOINs, subqueries, window functions, and indexing',
     'sql,database,learning',
     'USERNAME',
     'DATA_DATE',
     'USERNAME',
     'DATA_DATE'),

    ('Research Paper Notes',
     'https://arxiv.org/abs/2311.0123',
     'research',
     'Key findings from recent paper on database optimization techniques',
     'research,database,optimization',
     'USERNAME',
     'DATA_DATE',
     'USERNAME',
     'DATA_DATE'),

    ('Weekly Retrospective',
     '',
     'journal',
     'This week accomplishments: Completed database schema, implemented user auth, started on frontend',
     'journal,weekly-review,progress',
     'USERNAME',
     'DATA_DATE',
     'USERNAME',
     'DATA_DATE'),

    ('API Documentation Notes',
     'https://swagger.io/docs',
     'learning',
     'REST API best practices and OpenAPI specification guidelines',
     'api,documentation,rest',
     'USERNAME',
     'DATA_DATE',
     'USERNAME',
     'DATA_DATE'),

    ('Data Migration Plan',
     '',
     'project',
     'Steps for data migration: 1) Export legacy data 2) Transform 3) Validate 4) Import',
     'data-migration,planning,database',
     'USERNAME',
     'DATA_DATE',
     'USERNAME',
     'DATA_DATE'),

    ('Code Review Guidelines',
     'https://google.github.io/eng-practices',
     'learning',
     'Best practices for code review: 1) Check design 2) Verify functionality 3) Ensure maintainability',
     'code-review,best-practices,development',
     'USERNAME',
     'DATA_DATE',
     'USERNAME',
     'DATA_DATE');